//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using CIS494CourseProject.Model;
using SQLite;
using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace CIS494CourseProject
{
    public partial class SQLiteDb
    {
        public void AddFoodTransaction(FoodTransaction foodTrans)
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                //var foodTransTable = db.Table<FoodTransaction>();

                db.Insert(foodTrans);
            }
        }

        public List<FoodTransaction> GetFoodTransactionsUser()
        {
            List<FoodTransaction> result = new List<FoodTransaction>();

            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                var foodTransTable = db.Table<FoodTransaction>();

                foreach (var trans in foodTransTable)
                {
                    if (trans.UserID == Globals.UserID)
                    {
                        result.Add(trans);
                    }
                }

            }
            return result;
        }

    }
}
